datasets:
  - dataset_name: jigsaw_toxicity_pred
    dataset_dir: jigsaw
    template_file_path: templates/jigsaw-toxicity-pred-templates.yaml
    data_split: "train"

models:
  - name: roberta-mnli
    device: cuda

num_training_examples:
  - 10
  - 50
  - 100
  - 250
  - 500
  - 750
  - 1000

no_data_balance:
  - False
  - True
