datasets:
  - dataset_name: jigsaw_toxicity_pred
    dataset_dir: jigsaw
    template_file_path: templates/jigsaw-toxicity-pred-templates.yaml
    data_split: "train"
  - dataset_name: jigsaw_unintended_bias
    dataset_dir: jigsaw_unintended_bias
    template_file_path: templates/jigsaw-unintended-bias-templates.yaml
    data_split: "train"
    thresholds: [0.6]

models:
  - name: deberta
    device: cuda

num_training_examples:
  - 500
  - 1000
  - 2000

no_data_balance:
  - True
